### ISSUE TITLE
Implement model saving and loading

### ISSUE THREAD

**Issue by Michael0x2a** [Michael0x2a/nlp-capstone#5]
Implement code to save and load trained model. Probably dependent on #3 

- [x] Bag-of-words model
- [x] Logistic regression model
- [x] RNN model

Tasks 2 and 3 can probably be combined, since they both use tensorflow?

**Comment by briankchan** [comment]
I have manual saving in the character n-gram logistic regression model, although I'd like to make a minor tweak so it can save with arbitrary filenames in arbitrary paths (probably have to pass those in separately?).

We can also have automatic saving every X epochs while training, but I don't think that's all that useful unless training is so long that we're afraid things will break before training completes.
